### ISSUE TITLE
Allow unicode in filter names and other options

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#18]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mperrin](https://github.com/mperrin)**
_Thursday Sep 25, 2014 at 22:58 GMT_
_Originally opened as https://github.com/mperrin/webbpsf/issues/18_

----

Bug report from Brian York:

```
A quick update.

On the one hand, issue diagnosed and worked around. It turns out 
that webbpsf can't deal with filter names in unicode, so by explicitly 
encoding filters as ASCII before passing them in I avoid crashes.

On the other hand, not handling unicode strings is probably something 
to fix if you should ever happen to have the time and resources.
```

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Thursday Sep 25, 2014 at 22:59 GMT_

----

More detail from Brian, from his email 2014 July 14 :

The errors I'm getting are as follows. When running the simulator, and
creating a MIRI PSF, I get:

Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line
240, in trace_task
   R = retval = fun(_args, *_kwargs)
 File "/webapp/simulator.py", line 52, in **call**
   return TaskBase.**call**(self, _args, *_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line
437, in **protected_call**
   return self.run(_args, *_kwargs)
 File "/webapp/simulator.py", line 113, in simulate
   psf_fits = obs.AddError()
 File "/webapp/lib/ObservationModule.py", line 198, in AddError
   psf_data,psf_pixel_scale_x,psf_pixel_scale_y =
self._image.ConvolvePSF()
 File "/webapp/lib/JwstImage.py", line 342, in ConvolvePSF
   psf = ins.calcPSF(oversample=self._scaleFactor)
 File "/usr/local/lib/python2.7/dist-packages/webbpsf/webbpsf.py", line
367, in calcPSF
   wavelens, weights = self._getWeights(source=source, nlambda=nlambda,
monochromatic=monochromatic)
 File "build/bdist.linux-x86_64/egg/poppy/instrument.py", line 634, in
_getWeights
 File "/usr/local/lib/python2.7/dist-packages/webbpsf/webbpsf.py", line
565, in _getSynphotBandpass
   filterdata = atpy.Table(self._filter_files[wf], type='fits')
TypeError: only integer arrays with one element can be converted to an
index

The key point is that calcPSF dies off somewhere in atpy.Table I think,
and I'm not sure what's happening. I _do_ have astropy installed, so if
removing atpy would be helpful I can try that.

The second is in trying to figure out what was happening. In this case, I
started up a shell on the test server and started python and did the
sample webbpsf scripting code, which got me this error:

import os
os.environ['PYSYN_CDBS'] = "/webapp/sim_input/cdbs"
from webbpsf import *
nc = NIRCam()
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/local/lib/python2.7/dist-packages/webbpsf/webbpsf.py", line
760, in **init**
   JWInstrument.**init**(self, "NIRCam") # do this after setting the long
& short scales.
 File "/usr/local/lib/python2.7/dist-packages/webbpsf/webbpsf.py", line
145, in **init**
   filter_table = atpy.Table(self._WebbPSF_basepath + os.sep+
'filters.txt',type='ascii',delimiter='\t')
 File "/usr/local/lib/python2.7/dist-packages/atpy/basetable.py", line
168, in __init__
   self.read(_args, *_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/atpy/basetable.py", line
214, in read
   registry._readers[table_type](self, *args, **kwargs)
 File "<string>", line 2, in read_ascii
 File "/usr/local/lib/python2.7/dist-packages/atpy/decorators.py", line
44, in _auto_download_to_file
   return read(table, filename, _args, *_kwargs)
 File "<string>", line 2, in read_ascii
 File "/usr/local/lib/python2.7/dist-packages/atpy/decorators.py", line
56, in _auto_decompress_to_fileobj
   header = open(filename, 'rb').read(4)
IOError: [Errno 20] Not a directory:
'/usr/local/lib/python2.7/dist-packages/poppy-0.2.8-py2.7.egg/data/filters.
txt'
mi = MIRI()
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/local/lib/python2.7/dist-packages/webbpsf/webbpsf.py", line
591, in __init__
   JWInstrument.**init**(self, "MIRI")
 File "/usr/local/lib/python2.7/dist-packages/webbpsf/webbpsf.py", line
145, in **init**
   filter_table = atpy.Table(self._WebbPSF_basepath + os.sep+
'filters.txt',type='ascii',delimiter='\t')
 File "/usr/local/lib/python2.7/dist-packages/atpy/basetable.py", line
168, in __init__
   self.read(_args, *_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/atpy/basetable.py", line
214, in read
   registry._readers[table_type](self, *args, **kwargs)
 File "<string>", line 2, in read_ascii
 File "/usr/local/lib/python2.7/dist-packages/atpy/decorators.py", line
44, in _auto_download_to_file
   return read(table, filename, _args, *_kwargs)
 File "<string>", line 2, in read_ascii
 File "/usr/local/lib/python2.7/dist-packages/atpy/decorators.py", line
56, in _auto_decompress_to_fileobj
   header = open(filename, 'rb').read(4)
IOError: [Errno 20] Not a directory:
'/usr/local/lib/python2.7/dist-packages/poppy-0.2.8-py2.7.egg/data/filters.
txt'

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Wednesday Nov 19, 2014 at 04:29 GMT_

----

Cannot reproduce on current master. This was probably an `atpy` issue, now irrelevant since we switched to `astropy.table` for the FITS table IO. 

Test case added anyway in commit 011022c
