### ISSUE TITLE
Distortion only works with output_mode="both"

### ISSUE THREAD

**Issue by ariedel** [spacetelescope/webbpsf#228]
Attempting to run existing code (the Pandeia PSF library generator) with WebbPSF 0.7.0 results in a crash when trying to create the distortion planes.

```
Traceback (most recent call last):
  File "../make_psf2.py", line 874, in <module>
    generator.create_psfs(n_cores)
  File "../make_psf2.py", line 197, in create_psfs
    self.setup_psfs(n_cores,wavelengths)
  File "../make_psf2.py", line 241, in setup_psfs
    self._split_multi(n_cores,psfs)
  File "../make_psf2.py", line 443, in _split_multi
    self._get_pupil_throughput(psfs[0])
  File "../make_psf2.py", line 428, in _get_pupil_throughput
    monochromatic=inputs['wave'])
  File "/Users/riedel/anacondab/envs/pandeia_9/lib/python3.6/site-packages/webbpsf/webbpsf_core.py", line 797, in calc_psf
    psf[ext_new].header["EXTNAME"] = psf[ext].header["EXTNAME"][0:4] + "DIST"  # change extension name
  File "/Users/riedel/anacondab/envs/pandeia_9/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 317, in __getitem__
    raise e
  File "/Users/riedel/anacondab/envs/pandeia_9/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 313, in __getitem__
    self._positive_index_of(key))
  File "/Users/riedel/anacondab/envs/pandeia_9/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1044, in _try_while_unread_hdus
    return func(*args, **kwargs)
IndexError: list index out of range
```

The solution was to set output_mode="oversample" to output_mode="both", so that the distorted planes would be 2 and 3.

...As a secondary issue, there does not seem to be a way to get ONLY the oversampled distortion plane as an output. I can obviously copy that plane into a new fits file...

**Comment by mperrin** [comment]
This has been fixed in PR #219 by @shanosborne, shortly after the 0.7.0 release. It'll be included in the upcoming 0.8 release or you could run from master if you wanted the fix now. 

@shanosborne, see @ariedel's question above: with that fix in place, is it now possible to output only the oversampled distorted plane, if so desired?

**Comment by shanosborne** [comment]
No, as the code is currently set up, there is no way to return only the oversampled distorted PSF (same for the detector sampled distorted PSF). However it would be possible to add this functionality in if it's desirable.

**Comment by shanosborne** [comment]
And I'll add that if you want the immediate fix, you will need to also have the master of poppy (alongside the master of webbpsf) - both packages had updates to fix the output_mode issue.

**Comment by mperrin** [comment]
@ariedel @shanosborne Is this still needed as an open issue? Shannon's #219 fixed the underlying bug I think. Is it important to you @ariedel to be able to get only the oversampled distortion plane, or is it sufficient that you can use the workaround of just copying that plane into a new file?

**Comment by ariedel** [comment]
This is not needed; I have implemented the workaround of copying the plane I want into a new file.

**Comment by mperrin** [comment]
Thanks! OK then I think we can call this one complete.
